name: Validate New Dataset Issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  lint-dataset-issue:
    if: contains(github.event.issue.title, '[dataset]')
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue body
        id: body
        run: |
          printf "BODY<<'EOF'\n%s\nEOF\n" "${{ github.event.issue.body }}" >> $GITHUB_OUTPUT

      - name: Basic field validation
        id: validate
        run: |
          BODY="${{ steps.body.outputs.BODY }}"

          missing=()

          # Minimal checks for the New Dataset Intake template fields
          grep -qi 'source url' <<<"$BODY" || missing+=("Source URL / API endpoint")
          grep -qi 'license'    <<<"$BODY" || missing+=("License & Terms")
          grep -qi 'spatial & temporal coverage' <<<"$BODY" || missing+=("Spatial & Temporal Coverage")
          grep -qi 'formats & access' <<<"$BODY" || missing+=("Formats & Access")
          grep -qi 'preprocessing'    <<<"$BODY" || missing+=("Required Preprocessing / Transforms")
          grep -qi 'proposed dvc path' <<<"$BODY" || missing+=("Proposed DVC Path")
          grep -qi 'ethics & safety'   <<<"$BODY" || missing+=("Ethics & Safety")

          if [ ${#missing[@]} -gt 0 ]; then
            echo "MISSING<<EOF" >> $GITHUB_OUTPUT
            printf "%s\n" "${missing[@]}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Comment success
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            const body = `✅ Thanks! Your dataset issue contains the required sections.
- Our team will now review license compatibility, ethics, and reproducibility.
- If you have a minimal code example for a 1-tile AOI clip, please add it as a comment (optional).`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });

      - name: Comment missing fields
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const missing = `\n${{ steps.validate.outputs.MISSING || 'Unknown fields' }}`;
            const body = `⚠️ Some required fields appear missing in this dataset issue:
${missing}

Please edit the issue to include these sections.`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
